  class Solution {                                                                                                                                                                                                                                                                                                                           
  public:                                                                                                                                                                                                                                                                                                                                
      vector<int> dailyTemperatures(vector<int>& temperatures) {
          int n = temperatures.size();                                                                                                                                                                                                                                                                                                       
          vector<int> res(n, 0);                                                                                                                                                                                                                                                                                                             
          int stk[n], top = -1;                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                             
          for (int i = n - 1; i >= 0; --i) {                                                                                                                                                                                                                                                                                                 
              while (top != -1 && temperatures[stk[top]] <= temperatures[i])                                                                                                                                                                                                                                                                 
                  --top;                                                                                                                                                                                                                                                                                                                     
              res[i] = top == -1 ? 0 : stk[top] - i;                                                                                                                                                                                                                                                                                         
              stk[++top] = i;                                                                                                                                                                                                                                                                                                                
          }                                                                                                                                                                                                                                                                                                                                  
          return res;                                                                                                                                                                                                                                                                                                                        
      }                                                                                                                                                                                                                                                                                                                                  
  }; 
